name: Create an issue on push tag
on:
    push:
        tags:
            - v[0-9]* 
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      - name: get tag info
        id: tag-info
        run: echo "TAG_CONTENT=$(git show ${{github.ref_name}}  --pretty=format:"%H %an %s"
        )" >> $GITHUB_OUTPUT
        # run: echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)'${GITHUB_REF#refs/*/})" >> $GITHUB_OUTPUT
      - uses: dacbd/create-issue-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
            token: ${{ secrets.GITHUB_TOKEN }}
            title: RELEASE ${{ github.ref_name }}
            labels: RELEASE
            # body: ${{ steps.tag-info.outputs }}
            body: |
              Release: ${{ github.ref_name }}
              Author: ${{ github.actor }}
              Info: ${{ steps.tag-info.outputs.TAG_CONTENT }}
