name: Create an issue on push tag
on:
    push:
        tags:
            - v[0-9]* 
permissions:
  contents: read
  issues: write 
jobs:
  stuff:
    runs-on: ubuntu-latest
    steps:
        
      - uses: actions/checkout@v3
      - name: get tag info
        id: tag-info
        run: git show ${{github.ref_name}} >> $GITHUB_OUTPUT
      - uses: dacbd/create-issue-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with: 
            token: ${{ secrets.GITHUB_TOKEN }}
            title: RELEASE ${{ github.ref_name }}
            labels: RELEASE
            body: ${{ steps.tag-info.outputs }}
