name: DEPLOY
on: workflow_dispatch
jobs:
  get_tag:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      tag: ${{ steps.last.outputs.TAG }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get last tag
        id: last
        run: |
          echo "TAG=$(git describe --tags --match v[0-9]* $(git rev-list --tags --max-count=1))" >> $GITHUB_OUTPUT

      - name: check if tag is ok
        id: ok
        run: echo ${{ steps.last.outputs.TAG }}

  perform-tests:
    needs: get_tag
    uses: ./.github/workflows/tests.yml
    with:
      update_issue: true
      tagname: ${{ needs.get_tag.outputs.tag }}

  deploy:
    needs: [perform-tests, get_tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
        if: ${{ github.ref == 'refs/heads/master' }}
      - run: |
          npm i
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: success()
      - name: close issue
        # Закрывает issue. Интересно, сработает ли в этот раз способ добычи тега... не сработал. Странное!
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE="RELEASE ${{ needs.get_tag.outputs.tag }}"
          ISSUE_ID=$(gh issue list --json number,title -q \ ".[] | select(.title == \"${ISSUE_TITLE}\") | .number")
          gh issue close $ISSUE_ID -c "Release successfully deployed to [https://zayarnaya.github.io/unit-demo-cra/](https://zayarnaya.github.io/unit-demo-cra/)" -r "completed"
