name: auto testing
on:
  pull_request:
  workflow_call:
    inputs:
      update_issue:
        type: boolean
      tagname:
        type: string
# Запускает юнит-тесты, если запускается из экшна деплоя - апдейтит issue
# Ссылки получается две, но ведут они на выполнение всего workflow
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - run: npm test
        if: ${{ inputs.update_issue }}
      - name: Get Current Job Log URL
        uses: Tiryoh/gha-jobid-action@v0
        id: jobs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          job_name: "unit-test"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          ISSUE_TITLE="RELEASE ${{ inputs.tagname }}"
          ISSUE_ID=$(gh issue list --json number,title -q \ ".[] | select(.title == \"${ISSUE_TITLE}\") | .number")
          gh issue comment ${ISSUE_ID} --body "[WORKFLOW RUN](https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks/${{ github.run_id }}) \n\n [UNIT TESTS RUN](${{ steps.jobs.outputs.html_url }})"
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Запускает e2e-тесты, если запускается из экшна деплоя - апдейтит issue
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run build
      - run: npm run e2e
        if: ${{ inputs.update_issue }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          ISSUE_TITLE="RELEASE ${{ inputs.tagname }}"
          ISSUE_ID=$(gh issue list --json number,title -q \ ".[] | select(.title == \"${ISSUE_TITLE}\") | .number")
          gh issue comment ${ISSUE_ID} --body "[TESTS RUN E2E TESTS](https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks/${{ github.run_id }}) "
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
